<a href="https://colab.research.google.com/github/Oluwasemilore00/Data-Science/blob/main/Gender%20Score%20Comparison/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = df = pd.read_csv('StudentsPerformance.csv')

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
def separate_math_scores(df):

    # Create two lists
    Scores_above_70 = []
    Scores_seventy_and_below = []

    # Loop through math scores
    for score in df['math score']:

        # Append scores to appropriate list
        if score > 70:
            Scores_above_70.append(score)
        else:
            Scores_seventy_and_below.append(score)

    return Scores_above_70, Scores_seventy_and_below


high_scores, low_scores = separate_math_scores(df)

print("Scores above 70:", high_scores)
print("Scores 70 and below:", low_scores)

print("Number of scores above 70:", len(high_scores))
print("Number of scores 70 and below:", len(low_scores))

Scores above 70: [72, 90, 76, 71, 88, 78, 88, 74, 73, 97, 81, 74, 75, 82, 77, 88, 71, 82, 79, 80, 72, 73, 76, 71, 73, 71, 79, 78, 79, 85, 98, 87, 77, 99, 84, 75, 78, 79, 91, 88, 83, 87, 72, 82, 89, 87, 75, 74, 71, 76, 88, 88, 73, 100, 77, 82, 75, 81, 96, 72, 94, 79, 81, 71, 97, 80, 77, 76, 77, 78, 74, 82, 81, 74, 80, 87, 84, 83, 87, 86, 72, 88, 76, 92, 83, 80, 84, 73, 80, 75, 85, 89, 71, 80, 78, 79, 99, 76, 88, 71, 88, 83, 85, 73, 73, 81, 97, 88, 77, 76, 86, 78, 71, 90, 81, 80, 74, 99, 73, 71, 77, 83, 75, 71, 82, 82, 71, 90, 83, 76, 79, 72, 77, 75, 87, 80, 85, 73, 84, 74, 82, 80, 85, 71, 80, 87, 79, 73, 73, 77, 76, 85, 74, 88, 82, 87, 84, 71, 84, 71, 74, 82, 86, 73, 75, 75, 89, 78, 73, 79, 86, 81, 100, 79, 100, 72, 71, 77, 75, 84, 72, 77, 91, 83, 90, 71, 76, 80, 76, 73, 79, 83, 81, 76, 74, 94, 95, 82, 79, 86, 76, 77, 76, 74, 71, 91, 79, 73, 85, 97, 75, 79, 81, 82, 78, 92, 72, 79, 79, 87, 77, 73, 74, 96, 92, 71, 91, 74, 81, 81, 77, 73, 71, 74, 92, 76, 84, 75, 85, 94, 82, 88, 95, 100, 100, 79, 75, 84, 71, 80, 86, 76, 74, 72, 74, 85, 73, 77, 90, 74, 73, 80, 77, 73, 81, 73, 81, 94, 85, 77, 93, 73, 77, 79, 75, 79, 87, 89, 93, 80, 98, 81, 76, 73, 96, 76, 91, 74, 81, 73, 87, 92, 81, 80, 81, 72, 87, 71, 79, 77, 84, 78, 74, 76, 75, 72, 94, 77, 76, 91, 72, 89, 76, 87, 82, 73, 75, 90, 87, 72, 94, 77, 85, 78, 71, 74, 77, 73, 75, 74, 90, 91, 80, 71, 87, 82, 97, 75, 87, 81, 71, 97, 82, 78, 82, 90, 80, 81, 71, 93, 86, 85, 88, 85, 73, 93, 88, 79, 100, 91, 72, 74, 74, 98, 85, 77, 72, 78, 81, 82, 94, 75, 74, 72, 84, 92, 75, 100, 72, 75, 89, 78, 91, 81, 79, 78, 74, 81, 86, 88, 77]
Scores 70 and below: [69, 47, 40, 64, 38, 58, 40, 65, 50, 69, 18, 46, 54, 66, 65, 44, 69, 69, 67, 70, 62, 69, 63, 56, 40, 50, 57, 55, 58, 53, 59, 50, 65, 55, 66, 57, 53, 53, 33, 52, 58, 0, 39, 62, 69, 59, 67, 45, 60, 61, 39, 58, 63, 41, 61, 49, 44, 30, 61, 62, 47, 49, 50, 42, 58, 65, 27, 43, 65, 63, 58, 65, 68, 60, 58, 66, 52, 70, 62, 54, 51, 51, 55, 63, 65, 51, 53, 58, 51, 70, 59, 59, 42, 57, 22, 68, 62, 59, 54, 62, 70, 66, 60, 61, 66, 49, 52, 53, 58, 68, 67, 63, 43, 46, 52, 62, 46, 50, 65, 45, 65, 62, 48, 66, 62, 69, 61, 59, 55, 45, 67, 65, 69, 57, 59, 58, 35, 42, 60, 34, 66, 61, 56, 55, 52, 45, 57, 68, 46, 67, 63, 64, 54, 56, 59, 58, 65, 68, 47, 60, 54, 62, 64, 70, 65, 64, 44, 59, 63, 69, 69, 58, 47, 65, 59, 65, 53, 45, 70, 37, 67, 63, 65, 67, 46, 40, 56, 67, 69, 51, 53, 49, 66, 67, 68, 59, 63, 56, 67, 43, 41, 61, 28, 41, 47, 62, 61, 49, 24, 35, 58, 61, 69, 67, 62, 52, 66, 63, 46, 59, 61, 63, 42, 59, 58, 52, 27, 59, 49, 69, 61, 44, 45, 59, 46, 66, 38, 38, 67, 64, 57, 62, 57, 65, 48, 50, 60, 59, 53, 49, 54, 63, 65, 52, 70, 63, 51, 68, 57, 57, 47, 59, 41, 62, 69, 65, 68, 64, 61, 61, 47, 50, 70, 67, 59, 67, 69, 47, 64, 65, 65, 53, 37, 53, 53, 54, 26, 63, 68, 59, 55, 52, 68, 59, 49, 70, 61, 60, 64, 65, 64, 54, 68, 54, 59, 66, 63, 40, 68, 55, 64, 62, 54, 66, 66, 67, 69, 54, 53, 68, 56, 36, 29, 62, 68, 47, 62, 66, 51, 51, 64, 62, 40, 53, 32, 55, 61, 53, 63, 63, 48, 48, 61, 63, 68, 53, 50, 40, 61, 48, 53, 63, 69, 65, 55, 44, 54, 48, 58, 68, 56, 30, 53, 69, 65, 54, 29, 60, 40, 61, 58, 69, 58, 65, 60, 37, 65, 35, 62, 58, 61, 69, 61, 49, 44, 67, 66, 67, 41, 70, 65, 59, 64, 50, 69, 51, 68, 65, 62, 69, 43, 55, 65, 50, 63, 66, 52, 69, 65, 69, 50, 70, 63, 67, 60, 62, 29, 62, 53, 49, 66, 49, 59, 57, 66, 57, 63, 59, 62, 46, 66, 42, 60, 62, 55, 50, 47, 65, 68, 53, 68, 55, 55, 53, 67, 53, 61, 37, 59, 55, 69, 69, 50, 68, 58, 55, 70, 52, 69, 53, 48, 62, 60, 58, 68, 58, 52, 52, 62, 66, 49, 66, 35, 46, 52, 32, 19, 68, 52, 48, 60, 66, 42, 57, 70, 70, 69, 52, 67, 64, 41, 59, 51, 45, 54, 45, 61, 60, 49, 48, 62, 56, 65, 69, 68, 61, 64, 58, 60, 58, 66, 39, 64, 23, 40, 64, 59, 61, 62, 65, 52, 53, 39, 59, 61, 49, 59, 70, 43, 57, 59, 64, 63, 64, 55, 51, 62, 54, 69, 44, 50, 59, 32, 36, 63, 67, 65, 34, 67, 57, 67, 70, 50, 69, 52, 47, 46, 68, 44, 57, 69, 35, 54, 64, 65, 46, 48, 67, 62, 61, 70, 70, 67, 57, 61, 58, 54, 49, 49, 57, 58, 62, 45, 56, 48, 65, 62, 66, 63, 68, 53, 49, 54, 64, 60, 62, 55, 8, 57, 40, 44, 67, 65, 55, 62, 63, 62, 59, 68]
Number of scores above 70: 391
Number of scores 70 and below: 609

In [ ]:
def compare_math_scores_by_gender(data):

    # Filter rows by gender
    male_students = data[data['gender'] == 'male']
    female_students = data[data['gender'] == 'female']

    # Create lists of math scores
    male_scores = male_students['math score'].tolist()
    female_scores = female_students['math score'].tolist()

    # Compute averages
    male_avg = sum(male_scores) / len(male_scores)
    female_avg = sum(female_scores) / len(female_scores)

    # Print comparison
    print("Average Male Math Score:", round(male_avg, 2))
    print("Average Female Math Score:", round(female_avg, 2))


    if male_avg > female_avg:
        print("Pattern Detected: Male students perform better in math on average.")
    elif female_avg > male_avg:
        print("Pattern Detected: Female students perform better in math on average.")
    else:
        print("Pattern Detected: Both genders perform equally in math.")


compare_math_scores_by_gender(df)

Average Male Math Score: 68.73
Average Female Math Score: 63.63
Pattern Detected: Male students perform better in math on average.